// utils/Bootstrap template/DEVELOPER/Angular_5/blank/src/app/+outlook/outlook.component.ts
import {Component, OnInit} from '@angular/core';
import {ActivatedRoute, Router} from "@angular/router";
import {Subscription} from "rxjs/Subscription";
import {Outlook, Folder} from "./shared/outlook";
import {OutlookService} from "./shared/outlook.service";
import {FadeInTop} from "../shared/animations/fade-in-top.decorator";

@FadeInTop()
@Component({
  selector: 'sa-outlook',
  templateUrl: './outlook.component.html',
})
export class OutlookComponent implements OnInit {

  outlook:Outlook;
  outlookSub:Subscription;

  activeFolderKey:string;
  activeFolder:Folder;
  activeFolderSub:Subscription;

  constructor(private route:ActivatedRoute,
              private router:Router,
              private outlookService:OutlookService) {
    this.outlook = new Outlook();
    this.activeFolder = new Folder()
  }


  ngOnInit() {
    this.outlookSub = this.outlookService.getOutlook().subscribe(
      outlook => {
        this.outlook = outlook
      }
    );

    this.activeFolderSub = this.outlookService.activeFolder.subscribe(
      folder => {
        this.activeFolderKey = folder;
        if (this.outlook.folders) {
          this.activeFolder = this.outlook.folders.find(it=>it.key == folder)
        }
      }
    )
  }

  ngOnDestroy() {
    this.outlookSub.unsubscribe();
    this.activeFolderSub.unsubscribe();
  }

  deleteSelected(){
    this.outlookService.deleteSelected()
  }

}

<div id="content" class="sa-outlook-content">
  <div class="inbox-nav-bar no-content-padding">

    <h1 class="page-title txt-color-blueDark hidden-tablet"><i class="fa fa-fw fa-inbox"></i> Inbox </h1>

    <div class="btn-group visible-tablet" dropdown>
      <button class="btn btn-default dropdown-toggle" dropdownToggle>
        {{activeFolder?.name}} <i class="fa fa-caret-down"></i>
      </button>
      <ul class="dropdown-menu" *dropdownMenu>
        <li [class.active]="folder.key == activeFolder.key" *ngFor="let folder of outlook.folders">
          <a [routerLink]="[folder.key]">{{folder.name}} <i
            *ngIf="folder.key == activeFolder.key" class="fa fa-check"></i></a>
        </li>
      </ul>

    </div>

    <div class="inbox-checkbox-triggered">

      <div class="btn-group">
        <a placement="bottom"
           tooltip="Mark Important" class="btn btn-default"><strong><i
          class="fa fa-exclamation fa-lg text-danger"></i></strong></a>
        <a placement="bottom"
           tooltip="Move to folder" class="btn btn-default"><strong><i
          class="fa fa-folder-open fa-lg"></i></strong></a>
        <a (click)="deleteSelected()" placement="bottom"
           tooltip="Delete" class="deletebutton btn btn-default"><strong><i
          class="fa fa-trash-o fa-lg"></i></strong></a>
      </div>

    </div>

    <a id="compose-mail-mini"
       class="btn btn-primary pull-right hidden-desktop visible-tablet"> <strong><i
      class="fa fa-file fa-lg"></i></strong> </a>

    <div class="btn-group pull-right inbox-paging">
      <a class="btn btn-default btn-sm"><strong><i
        class="fa fa-chevron-left"></i></strong></a>
      <a class="btn btn-default btn-sm"><strong><i
        class="fa fa-chevron-right"></i></strong></a>
    </div>
    <span class="pull-right"><strong>1-30</strong> of <strong>{{activeFolder.total}}</strong></span>

  </div>

  <div id="inbox-content" class="inbox-body no-content-padding">

    <div class="inbox-side-bar">

      <a [routerLink]="['compose']" id="compose-mail" class="btn btn-primary btn-block">
        <strong>Compose</strong> </a>

      <h6> Folder <a tooltip="Refresh" placement="right" class="pull-right txt-color-darken"><i
        class="fa fa-refresh"></i></a></h6>

      <ul class="inbox-menu-lg">
        <li [class.active]="folder.key == activeFolder.key" *ngFor="let folder of outlook.folders">
          <a [routerLink]="[folder.key]"> {{folder.name}} <span *ngIf="folder.unread">({{folder.unread}})</span>
          </a>

        </li>
      </ul>

      <h6> Quick Access <a placement="right"
                           data-tooltip="Add Another" class="pull-right txt-color-darken"><i
        class="fa fa-plus"></i></a></h6>

      <ul class="inbox-menu-sm">
        <li *ngFor="let label of outlook.labels">
          <a>{{label.name}} ({{label.total}})</a>
        </li>
      </ul>

      <div class="air air-bottom inbox-space" *ngIf="outlook.space">

        {{outlook.space.free}} of <strong>{{outlook.space.total}}</strong><a data-tooltip="Empty Spam"
                                                                             data-placement="top"
                                                                             class="pull-right txt-color-darken"><i
        class="fa fa-trash-o fa-lg"></i></a>


        <div class="progress-micro">
          <progressbar value="{{outlook.space.ratio}}"></progressbar>
        </div>

      </div>

    </div>


    <router-outlet></router-outlet>

    <div class="inbox-footer">

      <div class="row">

        <div class="col-xs-6 col-sm-1">

          <div class="txt-color-white hidden-desktop visible-mobile" *ngIf="outlook.space">
            {{outlook.space.free}} of <strong>{{outlook.space.total}}</strong>
            <div class="progress-micro">
              <progressbar value="{{outlook.space.ratio}}"></progressbar>
            </div>
          </div>
        </div>

        <div class="col-xs-6 col-sm-11 text-right">
          <div class="txt-color-white inline-block">
            <i class="txt-color-blueLight hidden-mobile">Last account activity <i
              class="fa fa-clock-o"></i> 52 mins ago |</i> Displaying <strong>44 of 259</strong>
          </div>
        </div>

      </div>

    </div>

  </div>


</div>

// utils/Bootstrap template/DEVELOPER/ReactJS_15.x/full/src/app/routes/outlook/containers/Outlook.js
import React from 'react'
import {Dropdown, MenuItem, OverlayTrigger, Tooltip, ProgressBar} from 'react-bootstrap'
import {Link} from 'react-router'


import {bindActionCreators} from 'redux'
import {connect} from 'react-redux'
import {outlookInit} from '../OutlookActions'

class Outlook extends React.Component {
  componentWillMount() {
    this.props.dispatch(outlookInit())
  }

  render() {
    return (
      <div id="content">
        <div className="inbox-nav-bar no-content-padding">

          <h1 className="page-title txt-color-blueDark hidden-tablet"><i className="fa fa-fw fa-inbox"/> Outlook
          </h1>

          <Dropdown className="btn-group visible-tablet" id="inbox-select-folder-dropdown">
            <Dropdown.Toggle className="btn btn-default dropdown-toggle">
              {this.props.folder.name }
            </Dropdown.Toggle>
            <Dropdown.Menu className="dropdown-menu pull-left">
              {
                this.props.folders.map((_folder) => {
                  let check = _folder.key == this.props.params.folder ?
                    <i className="fa fa-check"/> : null;
                  return (
                    <MenuItem key={_folder.key} href={'#/outlook/folder/' + _folder.key}>
                      {_folder.name} {check}
                    </MenuItem>
                  )
                })
              }
            </Dropdown.Menu>
          </Dropdown>

          <div className="inbox-checkbox-triggered">
            <div className="btn-group">
              <OverlayTrigger placement="bottom"
                              overlay={<Tooltip id="mark0important-tooltip">Mark Important</Tooltip>}>
                <a className="btn btn-default"><strong><i
                  className="fa fa-exclamation fa-lg text-danger"/></strong></a>
              </OverlayTrigger>

              <OverlayTrigger placement="bottom"
                              overlay={<Tooltip id="move-to-folder-tooltip">Move to folder</Tooltip>}>
                <a className="btn btn-default"><strong><i className="fa fa-folder-open fa-lg"/></strong></a>
              </OverlayTrigger>

              <OverlayTrigger placement="bottom"
                              overlay={<Tooltip id="delete-message-tooltip">Delete</Tooltip>}>
                <a href="deleteSelected()" className="deletebutton btn btn-default"><strong><i
                  className="fa fa-trash-o fa-lg"/></strong></a>
              </OverlayTrigger>
            </div>
          </div>

          <a id="compose-mail-mini" className="btn btn-primary pull-right hidden-desktop visible-tablet">
            <strong><i className="fa fa-file fa-lg"/></strong> </a>

          <div className="btn-group pull-right inbox-paging">
            <a className="btn btn-default btn-sm"><strong><i className="fa fa-chevron-left"/></strong></a>
            <a className="btn btn-default btn-sm"><strong><i className="fa fa-chevron-right"/></strong></a>
          </div>
          <span
            className="pull-right"><strong>1-30</strong> of <strong>{this.props.folder.total}</strong></span>

        </div>

        <div id="inbox-content" className="inbox-body no-content-padding">

          <div className="inbox-side-bar">
            <Link to="/outlook/compose" id="compose-mail"
                  className="btn btn-primary btn-block"><strong>Compose</strong></Link>
            <h6> Folder
              <OverlayTrigger placement="right"
                              overlay={<Tooltip id="inbox-refresh-tooltip">Refresh</Tooltip>}>
                <a className="pull-right txt-color-darken"><i className="fa fa-refresh"/></a>
              </OverlayTrigger>
            </h6>

            <ul className="inbox-menu-lg">
              {this.props.folders.map((_folder, idx) =>{
                let unread = _folder.unread ? <span>({_folder.unread})</span> : null;
                return (
                  <li key={'inbox-sidebar-folder-' + idx}>
                    <Link to={'/outlook/folder/' + _folder.key}> {_folder.name} {unread}
                    </Link>
                  </li>
                )
              })}
            </ul>

            <h6> Quick Access
              <OverlayTrigger placement="right"
                              overlay={<Tooltip id="add-label-tooltip">Add Another</Tooltip>}>
                <a className="pull-right txt-color-darken"><i className="fa fa-plus"/></a>
              </OverlayTrigger>
            </h6>

            <ul className="inbox-menu-sm">
              {this.props.folder.labels.map((label, idx) => {
                return (
                  <li key={'folder-label' + idx}>
                    <a>{label.label} ({label.count})</a>
                  </li>
                )
              }) }
            </ul>

            <div className="air air-bottom inbox-space">
              {this.props.space.free} of <strong>{this.props.space.total}</strong>

              <OverlayTrigger placement="top"
                              overlay={<Tooltip id="empty-spam-tooltip">Empty Spam</Tooltip>}>
                <a className="pull-right txt-color-darken"><i className="fa fa-trash-o fa-lg"/></a>
              </OverlayTrigger>

              <ProgressBar bsStyle="success" className="progress-micro"
                           now={this.props.space.ratio}/>

            </div>
          </div>

          {this.props.children}

          <div className="inbox-footer">
            <div className="row">
              <div className="col-xs-6 col-sm-1">
                <div className="txt-color-white hidden-desktop visible-mobile">
                  {this.props.space.free} of <strong>{this.props.space.total}</strong>
                  <ProgressBar bsStyle="success" className="progress-micro"
                               now={this.props.space.ratio}/>
                </div>
              </div>

              <div className="col-xs-6 col-sm-11 text-right">
                <div className="txt-color-white inline-block">
                  <i className="txt-color-blueLight hidden-mobile">Last account activity <i
                    className="fa fa-clock-o"/> 52 mins ago |</i> Displaying <strong>44 of
                  259</strong>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

export default connect((state)=>(state.outlook))(Outlook)
