// utils/Bootstrap template/DEVELOPER/ReactJS_15.x/blank/src/app/routes/forms/jcrop/containers/DefaultPanel.js
import  React from 'react'

import {Provider} from 'react-redux'
import defaultBehaviorStore from '../stores/defaultDemoStore'

import JCrop from '../components/JCrop'
import Fields from '../components/Fields'
import ApiPanelControls from './ApiPanelControls'

export default ()=>(
    <Provider store={defaultBehaviorStore}>
        <div>
            <section>
                <JCrop

                    store={defaultBehaviorStore} src="assets/img/superbox/superbox-full-11.jpg" width={600} height={400}/>
            </section>
        </div>
    </Provider>
);

// utils/Bootstrap template/DEVELOPER/Angular_5/blank/src/app/+forms/+image-cropping/default-panel/default-panel.component.ts
import {Component, OnInit, Input} from '@angular/core';

import {NgRedux, select} from '@angular-redux/store'

@Component({
  selector: 'image-editor-default-panel',
  template: `
            <section>
                <jcrop
                    [storeId]="storeId" 
                    src="assets/img/superbox/superbox-full-11.jpg"
                    [width]="600" [height]="400"></jcrop>
            </section>
`,
})
export class DefaultPanelComponent implements OnInit {


  public storeId = 'defaultPanel';

  @Input() active: boolean;

  constructor(private ngRedux: NgRedux<any>) {

  }

  ngOnInit() {

  }


}
